import React, { useState } from 'react';
import { Image, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { PlaceMedia } from './demo-data';

export function Action({ title, onPress, small = false, disabled = false }: { title: string; onPress: () => void; small?: boolean; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [s.action, small && s.smallAction, { opacity: disabled ? 0.45 : pressed ? 0.7 : 1 }]}><Text style={[s.actionText, small && { fontSize: 12 }]}>{title}</Text></Pressable>;
}
export function PlacePhoto({ place }: { place: PlaceMedia }) {
  const [failed, setFailed] = useState(false);
  const [attempt, setAttempt] = useState(0);
  return <View>{failed ? <View style={[s.photo, s.center]}><Text style={s.body}>Photo could not load.</Text><Action small title="Retry photo" onPress={() => { setFailed(false); setAttempt(a => a + 1); }} /></View> : <Image key={attempt} accessibilityLabel={`Photograph of ${place.name}`} source={{ uri: place.photo }} onError={() => setFailed(true)} style={s.photo} resizeMode="cover" />}
    <Pressable accessibilityRole="link" onPress={() => Linking.openURL(place.source)}><Text style={[s.caption, { marginTop: 8, textDecorationLine: 'underline' }]}>{place.credit} ↗</Text></Pressable>
  </View>;
}
export const s = StyleSheet.create({
  routeStep: { flexDirection: 'row', gap: 10 },
  routeRail: { width: 16, position: 'relative', alignItems: 'center' },
  routeDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#ff9100', marginTop: 20, borderWidth: 2, borderColor: '#fff1df', zIndex: 1 },
  routeLine: { position: 'absolute', width: 2, top: 26, bottom: -26, backgroundColor: '#ffd5a9' },
  screen: { flex: 1, backgroundColor: '#fbf9f6' }, page: { padding: 16, paddingBottom: 120, gap: 18, width: '100%', maxWidth: 640, alignSelf: 'center' },
  row: { flexDirection: 'row', alignItems: 'center', gap: 9 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  heading: { fontSize: 17, fontWeight: '700', color: '#51392f' }, title: { fontSize: 25, fontWeight: '700', color: '#303638' }, label: { fontSize: 13, fontWeight: '600', color: '#503a31' }, body: { fontSize: 12, lineHeight: 19, color: '#655950' }, caption: { fontSize: 10, lineHeight: 15, color: '#947d70' }, sectionLabel: { fontSize: 15, color: '#925100', fontWeight: '700' },
  tag: { backgroundColor: '#f1e7dc', paddingHorizontal: 8, paddingVertical: 4, fontSize: 10, color: '#87604b', borderRadius: 7 }, search: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#fff', borderRadius: 13, borderWidth: 1, borderColor: '#eddfd2', paddingHorizontal: 13, height: 48 }, searchIcon: { fontSize: 25, color: '#9b7460' }, input: { flex: 1, fontSize: 14, color: '#51392f' },
  card: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#eddfd2', borderRadius: 18, padding: 15, gap: 8 }, result: { paddingVertical: 10, gap: 3 }, day: { paddingVertical: 8, paddingHorizontal: 16, backgroundColor: '#fff', borderRadius: 20, borderWidth: 1, borderColor: '#e8dfd5' }, selectedChip: { borderColor: '#995400', backgroundColor: '#fff4e5' }, progress: { height: 5, backgroundColor: '#ece6dc', borderRadius: 4 }, notice: { padding: 12, borderRadius: 12, backgroundColor: '#eaf2e3', color: '#49713b', fontSize: 12 },
  timelineRow: { flexDirection: 'row', gap: 13 }, rail: { width: 18, alignItems: 'center', paddingTop: 16 }, dot: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#ffce96', borderWidth: 3, borderColor: '#ffefdf' }, line: { width: 1, flex: 1, backgroundColor: '#ffb557', marginTop: 5 }, stopCard: { flex: 1, minWidth: 0, borderRadius: 18, borderWidth: 1, borderColor: '#eddfd2', padding: 14, marginBottom: 18, backgroundColor: '#fff' }, time: { color: '#e47700', fontSize: 11, fontWeight: '600' }, stopPhoto: { height: 152, width: '100%', borderRadius: 17, backgroundColor: '#e6e9eb' }, edit: { padding: 7 }, candidate: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderStyle: 'dashed', borderColor: '#dacabc', borderRadius: 16, backgroundColor: '#fff', padding: 15, marginLeft: 31 },
  action: { backgroundColor: '#ff9100', borderRadius: 14, minHeight: 50, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center' }, smallAction: { backgroundColor: '#ffcca0', minHeight: 31, borderRadius: 17, paddingHorizontal: 12 }, actionText: { fontSize: 15, fontWeight: '700', color: '#462900' }, discussion: { textAlign: 'center', fontSize: 13, color: '#8b4b00', padding: 8 }, sheet: { maxWidth: 480, alignSelf: 'center', backgroundColor: '#f3f7fa' }, photo: { width: '100%', aspectRatio: 1, backgroundColor: '#e3e9ed', borderRadius: 18 }, center: { justifyContent: 'center', alignItems: 'center', gap: 14 }, mediaTabs: { flexDirection: 'row', backgroundColor: '#e2e8ec', borderRadius: 12, padding: 4, marginVertical: 16 }, mediaTab: { flex: 1, borderRadius: 10, alignItems: 'center', paddingVertical: 11 }, divider: { height: 1, backgroundColor: '#d1d4d4', marginVertical: 16 }, info: { padding: 16, borderRadius: 15, backgroundColor: '#e9eff3', gap: 6 },
  liveIntro: { borderRadius: 18, backgroundColor: '#fff0de', padding: 16, gap: 5 }, member: { alignItems: 'center', gap: 4 }, avatar: { width: 35, height: 35, borderRadius: 18, borderWidth: 2, borderColor: '#fff', alignItems: 'center', justifyContent: 'center' }, initials: { fontSize: 10, fontWeight: '700', color: '#fff' }, routeCard: { borderWidth: 1, borderColor: '#e6e9ec', borderRadius: 25, backgroundColor: '#fff', padding: 16 }, routeTime: { fontSize: 15, fontWeight: '600', color: '#53585b' }, transport: { flex: 1, borderWidth: 1, borderColor: '#dce2e7', backgroundColor: '#f2f6f8', padding: 10, borderRadius: 13, minHeight: 54, alignItems: 'center', justifyContent: 'center' }, transportLabel: { fontSize: 10, color: '#51585b' }, aiPick: { position: 'absolute', top: -9, backgroundColor: '#975100', color: '#fff', borderRadius: 7, fontSize: 8, paddingHorizontal: 7, paddingVertical: 2 }, dropoff: { marginTop: 16, backgroundColor: '#eaf0f4', borderWidth: 1, borderColor: '#dfe5e9', borderRadius: 17, padding: 12, flexDirection: 'row', gap: 12 }, thumbnail: { width: 62, height: 74, borderRadius: 11, backgroundColor: '#d7dfe3' }, verified: { fontSize: 10, color: '#468a72', marginTop: 3 },
});
